/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] one = new int[1];
        int[] two = test(one);
        System.out.println(one == two);

    }
    
    public static int[] test(int[] input) {
        return input;
    }
}
